/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compi;



import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.io.BufferedWriter;
import java.io.IOException;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;



/**
 *
 * @author seati
 */
public class Interfaz extends javax.swing.JFrame {
  lexico Lex;
  sintaxis sintx;
  String arch;
  File file;
  String direccion="";
  
    
    public Interfaz() {
        
       
         initComponents();
        setTitle("Compilador");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNuevo1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEjecutar = new javax.swing.JButton();
        SemanticoLabel = new javax.swing.JLabel();
        SemanticoStatusLabel = new javax.swing.JLabel();
        LexicoLabel = new javax.swing.JLabel();
        LexicoStatusLabel = new javax.swing.JLabel();
        SintaxisLabel1 = new javax.swing.JLabel();
        SintaxisStatusLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Examinar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("AreaCodigo"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setFont(new Font("Monospaced",Font.PLAIN,12));
        JPanel panel = new JPanel(new BorderLayout());

        panel.add(jScrollPane1, BorderLayout.CENTER);

        JTextArea lineNumbers = new JTextArea("1");
        lineNumbers.setFont(new Font("Monospaced", Font.PLAIN, 12));
        lineNumbers.setBackground(Color.LIGHT_GRAY);
        lineNumbers.setEditable(false);
        jScrollPane1.setRowHeaderView(lineNumbers);

        jTextArea1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateLineNumbers();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateLineNumbers();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateLineNumbers();
            }

            private void updateLineNumbers() {
                SwingUtilities.invokeLater(() -> {
                    int lineCount = jTextArea1.getLineCount();
                    StringBuilder numbersText = new StringBuilder();
                    for (int i = 1; i <= lineCount; i++) {
                        if (i > 1) {
                            numbersText.append("\n");
                        }
                        numbersText.append(i);
                    }
                    lineNumbers.setText(numbersText.toString());
                });
            }
        });

        jButton2.setText("Compilar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Archivo");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Token", "Renglon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setText("Output");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Linea", "Tipo", "Nombre", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setText("Lista de lexemas");

        jLabel4.setText("Lista de variables");

        btnNuevo1.setText("Nuevo");

        btnGuardar.setText("Guardar");

        btnEjecutar.setText("Ejecutar");

        SemanticoLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SemanticoLabel.setText("3)Semantico");

        SemanticoStatusLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SemanticoStatusLabel.setText("-----------");

        LexicoLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LexicoLabel.setText("1)Lexico");

        LexicoStatusLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LexicoStatusLabel.setText("-----------");

        SintaxisLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SintaxisLabel1.setText("2)Sintaxis");

        SintaxisStatusLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SintaxisStatusLabel1.setText("-----------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LexicoLabel)
                        .addGap(13, 13, 13)
                        .addComponent(LexicoStatusLabel)
                        .addGap(24, 24, 24)
                        .addComponent(SintaxisLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(SintaxisStatusLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(SemanticoLabel)
                        .addGap(10, 10, 10)
                        .addComponent(SemanticoStatusLabel))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnNuevo1)
                                .addGap(15, 15, 15)
                                .addComponent(btnBuscar)
                                .addGap(22, 22, 22)
                                .addComponent(btnGuardar)
                                .addGap(16, 16, 16)
                                .addComponent(jButton2)
                                .addGap(175, 175, 175)
                                .addComponent(btnEjecutar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo1)
                            .addComponent(btnBuscar)
                            .addComponent(btnGuardar)
                            .addComponent(jButton2)
                            .addComponent(btnEjecutar))))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LexicoLabel)
                    .addComponent(LexicoStatusLabel)
                    .addComponent(SintaxisLabel1)
                    .addComponent(SintaxisStatusLabel1)
                    .addComponent(SemanticoLabel)
                    .addComponent(SemanticoStatusLabel))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "TXT Files", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " + chooser.getSelectedFile().getName());
            file=chooser.getSelectedFile();
            arch=chooser.getSelectedFile().getAbsolutePath();
            direccion=arch;
            try {
            String contenido = new String(Files.readAllBytes(file.toPath()));
            jTextArea1.setText(contenido);
            //jTextArea1.read(new BufferedReader(new FileReader(arch)), null);
            

        } catch (Exception e){

            e.printStackTrace();
        }
        } else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona un archivo valido");
        }
    //Path
       
              
    }//GEN-LAST:event_btnBuscarActionPerformed

    
    private void Archivo(){
     try{
           PrintWriter writer = new PrintWriter(file);
        writer.print("");
        writer.close();
        
           
        FileWriter fw = new FileWriter(file.getAbsoluteFile(), true);
       
        jTextArea1.write(fw);
        
       
         Lex=new lexico(arch);
         if (Lex.errorEncontrado) {
             LexicoStatusLabel.setText("❌❌❌❌❌");
         }else{
             LexicoStatusLabel.setText("✅✅✅✅✅");
         }
         sintx = new sintaxis(Lex.cabeza);
         if (sintx.errorSintactico) {
             SintaxisStatusLabel1.setText("❌❌❌❌❌");
         }else{
             SintaxisStatusLabel1.setText("✅✅✅✅✅");
         }
         if (sintx.errorsemantico) {
             SemanticoStatusLabel.setText("❌❌❌❌❌");
         }else{
             SemanticoStatusLabel.setText("✅✅✅✅✅");
         }
         
         jTextArea2.setText(Lex.Impresion);
         
         jTextArea2.append("\n"+sintx.impresion);
         RecorrerNodos(Lex.cabeza);
         RecorrerVariables(sintx.cabezaVariables);
         
         Path path = Paths.get(direccion);
        String directory = path.getParent().toString();
         directory+="\\intermedio";
        /* System.out.println(extensionArchivo(direccion, "asm"));
         System.out.println("intermedio \n"+sintaxis.intermedio);*/
         
         try (BufferedWriter writer2 = new BufferedWriter(new FileWriter(extensionArchivo(directory, "txt"),false))) {
            
            writer2.write(sintaxis.intermedio);
            System.out.println("Data has been saved to the file.");
            writer2.close();
            IntermedioToMASM trad=new IntermedioToMASM(extensionArchivo(directory, "txt"),sintx.tempCount);
            sintx.tempCount=0;
        } catch (IOException e) {
            e.printStackTrace();
        }
         
       
       } catch(Exception e){
           System.out.println(e);
       }
    }
    
    private String extensionArchivo(String path,String extension){
        int lastDotIndex = path.lastIndexOf('.');
        if (lastDotIndex != -1) {
            return path.substring(0, lastDotIndex + 1) + extension;
        } else {
            return path + "." + extension;
        }
    }
    
    private void RecorrerNodos(nodo cabeza){
        nodo p=cabeza;
         DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.addColumn("Lexema");
        tableModel.addColumn("Token");
        tableModel.addColumn("Renglon");
        while (p!=null) {            
         tableModel.addRow(new Object[]{p.lexema,String.valueOf(p.token),String.valueOf(p.renglon)});
         p=p.sig;
        }
        jTable1.setModel(tableModel);
    }
    
    private void RecorrerVariables(TablaSimbolos cabeza){
    TablaSimbolos p=cabeza;
         DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.addColumn("Linea");
        tableModel.addColumn("Tipo");
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Valor");
        while (p!=null) {            
         tableModel.addRow(new Object[]{String.valueOf(p.numLinea),String.valueOf(p.tipo),String.valueOf(p.nombre),String.valueOf(p.valor)});
         p=p.siguiente;
        }
        jTable2.setModel(tableModel);
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Archivo();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LexicoLabel;
    private javax.swing.JLabel LexicoStatusLabel;
    private javax.swing.JLabel SemanticoLabel;
    private javax.swing.JLabel SemanticoStatusLabel;
    private javax.swing.JLabel SintaxisLabel1;
    private javax.swing.JLabel SintaxisStatusLabel1;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
